

class Vendor_Info_Model{

  String FIRM_NAME='';
  String OWNER_NAME='';
  String EMAIL_ID='';
  String PHONE_NUMBER='';
  String OFFICE_ADDRESS='';
  String AREA='';
  String PINCODE='';
  String CONCERN_PERSON='';
  String CONCERN_PERSON_EMAIL_ID='';
  String CONCERN_PERSON_PHONE_NUMBER='';
  String DOCTOR_CONSULTANTCONSULTANT='';
  String CONCERN_EMAIL_ID='';
  String CONSULTANT_PHONE_NUMBER='';
  String FARM_ADDRESS='';
  String CONSULTANT_AREA='';
  String CONSULTANT_PINCODE='';
  String BREED_NAME='';
  String ADDITIONAL_INFORMATION='';
  String MARKETING_PERSON_EMAIL_ID='',SALES_PERSON_EMAIL_ID='',DEALER_EMAIL_ID='',DISTRIBUTOR_EMAIL_ID='',EDITOR_EMAIL_ID='';
  String ASSOCIATION_EMAIL_ID='',MEMBER_EMAIL_ID='',LINE_SUPERVISOR_EMAIL_ID='',CONSULTANT_EMAIL_ID='',AGENT_EMAIL_ID='';
  String COMPANY_EMAIL_ID='',CA_EMAIL_ID='',MARKETING_PERSON_PHONE_NUMBER='',SALES_PERSON_PHONE_NUMBER='',DEALER_PHONE_NUMBER='';
  String DISTRIBUTOR_PHONE_NUMBER='',EDITOR_PHONE_NUMBER='',ASSOCIATION_PHONE_NUMBER='',MEMBER_PHONE_NUMBER='',LINE_SUPERVISOR_PHONE_NUMBER='',AGENT_PHONE_NUMBER='';
  String COMPANY_PHONE_NUMBER='',CA_PHONE_NUMBER='',TECHNICIAN_PHONE_NUMBER='',CONTACTPERSON_PHONE_NUMBER='',EDITOR_PHONE_NUMBERHOD_PHONE_NUMBER='',OUTLET_PHONE_NUMBER='';
  String CHICKEN_SHOP_AREA='',AREA_OF_WORKING='',AREA_SPECIFIC='',SALES_PERSON_AREA='',BRANCH_AREA='',AREA_OF_SUPPLY='',WAREHOUSE_AREA='',AREA_OF_DELIVERY='';
  String WORKING_AREA='',SUPPLY_AREA='',OUTLET_AREA='',DEALER_PINCODE='',CA_PINCODE='',CHICKEN_SHOP_PINCODE='',COMPANY_PINCODE='',CONCERN_PERSON_PINCODE='';
  String DISTRIBUTOR_PINCODE='',SALES_PERSON_PINCODE='',LINE_SUPERVISOR_PINCODE='',BRANCH_PINCODE='',OUTLET_PINCODE='',ASSOCIATION_PINCODE='',WAREHOUSE_PINCODE='';
  String CONCERN_PERSON_NAME='',ADDRESS='',CA_ADDRESS='',DEALER_ADDRESS='',CHICKEN_SHOP_ADDRESS='',COMPANY_ADDRESS='',FACTORY_ADDRESS='',BRANCH_ADDRESS='',LINE_SUPERVISOR_BRANCH_ADDRESS='';
  String AGENT_ADDRESS='',OUTLET_ADDRESS='',ASSOCIATION_ADDRESS='',WAREHOUSE_ADDRESS='',ABOUT_PRODUCT='',AGENT_NAME='',ANYTHING_TO_SPECIFY='',ANY_SPECIFIC_BREED='',ANY_THING_MORE_TO_SAY='';
  String ANY_THING_TO_SAY='',ANY_THING_TO_SPECIFY='',ASSOCIATION_DESIGNATION='',ASSOCIATION_MEMBER='',ASSOCIATION_NAME='',MANAGER_NAME='',BRANCH_NAME='',BREEDER_FARM_NAME='',CAPACITY='',
      CATEGAORY='',CATEGORY='',CA_CONCERN_PERSON='',CHICKEN_STORING_CAPACITY='',COMPANY_NAME='',COMPANY_WEBSITE='',COMPOSITION='',CONTACT_NUMBER='',CONTACT_PERSON='',CONTACT_PERSON_CONTACT_NUMBER='',
      DATE_OF_BIRTH='',DISTRIBUTOR_NAME='',DEALER_FIRM_NAME='',DEALER_NAME='',DEPO='',DESCRIPTION='',DIRECTOR_NAME='',MEMBER_NAME='',DISTRIBUTOR_OF_COMPANY='',DISTRIBUTOR_PIN_CODE='',DOCTOR='',CONSULTANT='',
      DOSE='',EDITOR_NAME='',EGG_STORING_CAPACITY='',EMAIL='',EMAI_ID='',EXHIBITION_NAME='',EXPERTISE='',FACILITY='',FORMULATION='',FULL_LOAD='',INSTITUTE_NAME='',INSTITUTION='',ENTREPRENEUR='',
      LAB_NAME='',LINE_SUPERVISOR='',LIST_OF_PROJECT='',LIST_OF_SERVICE='',MARKETING_PERSON='',MEMBER_DESIGNATION='',MOBILE_NUMBER='',MRP='',NAME='',OTHERS='',PACKING='',PARTNER_NAME='',
      PERSON_NAME='',PHONENUMBER='',PIN_CODE='',POSITION='',PRODUCT='',PRODUCT_DETAILS='',PRODUCT_NAME='',PRODUCT_USAGE='',HOD_NAME='',PUBLICATION_HOUSE='',QUALIFICATION='',RAW_MATERIAL_NAME='',
      REMARK='',RETAIL_OUTLET_NAME='',SALES_PERSON_NAME='',SOFTWARE_NAME='',SPECIALISATION='',MASTERS='',SPECIALISE_IN='',SPECIALITY='',SPECIES_NAME='',SPECIFICATION='',STATE='',SUBJECT='',
      SUBSIDY_LIST='',TECHNICIAN_EMAIL='',TECHNICIAN_NAME='',TRANSPORT_ID='',USED_FOR='',VALUE_ADDITION='',VALUE_ADDITION_REMARK='',WAREHOUSE='',WEBSITE='',WHICH_TYPE_OF_LABOUR='',TYPE_OF_CERTIFICATION='';
  //List<File> productImages=[];
  Vendor_Info_Model();
}
