// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      // case TargetPlatform.iOS:
      //   return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1rRlA1h9cPnyJUS0Qo1hPd61uUdGaIt8',
    appId: '1:331485042758:android:e4b0bbc73e1c2607ae5247',
    messagingSenderId: '1092536869888',
    projectId: 'poultrya2z-2538e',
    storageBucket: 'poultrya2z-2538e.appspot.com',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyD1rRlA1h9cPnyJUS0Qo1hPd61uUdGaIt8',
  //   appId: '1:1092536869888:ios:cbbbec6379c8d13cf7a4e5',
  //   messagingSenderId: '1092536869888',
  //   projectId: 'poultrya2z-2538e',
  //   storageBucket: 'poultrya2z-2538e.appspot.com',
  //   androidClientId: '331485042758-ev0g5cjg5smgpe342fm62tae8fp5jh6h.apps.googleusercontent.com',
  //   iosClientId: '1092536869888-g668d3sngute1oosld4tjkbagvd9iu8a.apps.googleusercontent.com',
  //   iosBundleId: 'com.geobull.geobullEcommerce',
  // );
}
