// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt8bj4UACvakZfiSy-0c1o_ivfplm7jEU',
    appId: '1:1092536869888:android:711ee88b66a6416df7a4e5',
    messagingSenderId: '1092536869888',
    projectId: 'ecommerce-appbuilder',
    storageBucket: 'ecommerce-appbuilder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8j52mmVX5Sz_DE2n-4MdKaCyZJlA0g90',
    appId: '1:1092536869888:ios:cbbbec6379c8d13cf7a4e5',
    messagingSenderId: '1092536869888',
    projectId: 'ecommerce-appbuilder',
    storageBucket: 'ecommerce-appbuilder.appspot.com',
    androidClientId: '1092536869888-jm5331ptkp60gfogh4qk263b6fb893td.apps.googleusercontent.com',
    iosClientId: '1092536869888-g668d3sngute1oosld4tjkbagvd9iu8a.apps.googleusercontent.com',
    iosBundleId: 'com.geobull.geobullEcommerce',
  );
}
